stages:
  - validate
  - plan
  - apply
  - destroy
  

variables:
  AWS_DEFAULT_REGION: us-east-1


.terraform:
  image:
    name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: "us-east-1"

  cache:
    paths:
      - .terraform

  before_script:
    - terraform --version
    - terraform init



validate:
  stage: validate
  script:
    - terraform validate
  extends:
    - .terraform

plan:
  stage: plan
  script:
    - terraform plan -out="planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
  extends:
    - .terraform

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  extends:
    - .terraform
  dependencies:
    - plan
  when: manual

destroy: 
  stage: destroy
  script:
    - terraform destroy --auto-approve
  extends:
    - .terraform
  when: manual 
